CREATE TABLE cart
(
    cart_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coupon_id    BIGINT,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_cart PRIMARY KEY (cart_id)
);

CREATE TABLE coupon
(
    coupon_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    coupon_code                VARCHAR(255),
    applicable_amount          DECIMAL,
    applicable_number_of_items BIGINT                                  NOT NULL,
    discount_amount            DECIMAL,
    discount_percent           DOUBLE PRECISION                        NOT NULL,
    apply_either               BOOLEAN                                 NOT NULL,
    created_date               TIMESTAMP WITHOUT TIME ZONE,
    updated_date               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_coupon PRIMARY KEY (coupon_id)
);

CREATE TABLE product
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cart_id      BIGINT,
    name         VARCHAR(255),
    price        DOUBLE PRECISION                        NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

ALTER TABLE cart
    ADD CONSTRAINT uc_cart_coupon UNIQUE (coupon_id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (cart_id);