INSERT INTO product (cart_id, name, price, created_date, updated_date)
VALUES
    (1, 'Product A', 50.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1, 'Product B', 30.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'Product C', 60.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'Product D', 40.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'Product E', 70.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'Product F', 80.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);